[package]
name = "messer"
version = "0.1.1"
edition = "2021"
authors = ["Belkanov Dmitriy <dbkkll@yandex.ru>"]

[dependencies]
clap = { version = "4.4.11", features = ["cargo"] }
regex = "1.10.2"
walkdir = "2.3"
