[package]
name = "messer"
version = "0.3.2"
edition = "2021"
authors = ["Belkanov Dmitriy <dbkkll@yandex.ru>"]

[dependencies]
clap = { version = "4.4.11", features = ["cargo"] }
nu-ansi-term = "0.49.0"
regex = "1.10.2"
thiserror = "1.0.50"
walkdir = "2.3"
